### ISSUE TITLE
404 in wiki "Compass configuration"

### ISSUE THREAD

**Issue by ZoomQuiet** [gdg-x/zeppelin#20]
http://compass-style.org/help/tutorials/configuration-reference
is lost...

**Comment by enigmatic-user** [comment]
A link to the old URL can still be found on http://compass-style.org/help/tutorials/. On the same page, the link to the "command line documentation" is broken, too; it should be http://compass-style.org/help/documentation/command-line/ instead of http://compass-style.org/help/tutorials/command-line/.

**Comment by ozasadnyy** [comment]
Thanks @enigmatic-user . I have fixed links.

**Comment by enigmatic-user** [comment]
Thank you very much for your quick response. I guess this isn't online yet? I don't know your deployment process... Or is there a server-side cache? Anyway, the changes aren't visible yet (it's not my browser cache).

**Comment by ozasadnyy** [comment]
Maybe I misunderstood you... I have changed these links http://take.ms/B5ktc

**Comment by enigmatic-user** [comment]
Sorry, my fault - I posted in the wrong tab...  \*lol\*
